# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-06 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(default='https://vk.com/lambdafrela', max_length=100)),
                ('description', models.TextField(max_length=1500)),
                ('slug', models.SlugField(blank=True, max_length=300)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('entry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registry.Entry')),
                ('date', models.DateTimeField()),
                ('address', models.CharField(max_length=300)),
                ('speaker', models.CharField(max_length=100)),
            ],
            bases=('registry.entry',),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('entry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registry.Entry')),
                ('github', models.URLField(default='https://github.com/lambdafrela', max_length=100)),
                ('email', models.EmailField(max_length=100)),
            ],
            bases=('registry.entry',),
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('entry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registry.Entry')),
            ],
            bases=('registry.entry',),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('entry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registry.Entry')),
                ('github', models.URLField(default='https://github.com/lambdafrela', max_length=100)),
            ],
            bases=('registry.entry',),
        ),
    ]
