# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-07 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_partner_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
