# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-08 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_entry_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.TextField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='event',
            name='speaker',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
