# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-09 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_auto_20160808_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='avatar',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
