# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-09 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0006_event_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='future',
            field=models.BooleanField(default=True),
        ),
    ]
