# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-01 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import registry.models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0012_auto_20160901_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=registry.models.get_image_dir_path),
        ),
    ]
