# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-01 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import registry.models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0013_auto_20160901_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='image',
            field=models.ImageField(null=True, upload_to=registry.models.get_image_dir_path),
        ),
    ]
