image: python:latest

stages:
  - staticcheck
  - test
  - build
#  - deploy

variables:
  CONTAINER_TEST_IMAGE: registry.gitlab.com/lambdait/lambdaweb
  CONTAINER_RELEASE_IMAGE: registry.gitlab.com/lambdait/lambdaweb:latest

build:
  image: docker:git
  services:
    - docker:dind
  before_script:
    - docker login -u murych -p $CI_BUILD_TOKEN registry.gitlab.com
  stage: build
  script:
    - docker build -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE
  only:
    - master

staticcheck:
  before_script:
    - pip install -U flake8
  script:
    - flake8 --config=tox.ini .
  stage: staticcheck

test:
  before_script:
    - pip install -Ur requirements.txt
    - python manage.py migrate
#    - python manage.py collectstatic --noinput
  script:
    - python manage.py test
  stage: test

#deploy to production:
#  stage: deploy
#  script: curl https://yourhost.com/deploy/${PRODUCTION_DEPLOY_KEY}/
#  environment: production
#  only:
#    - master