# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170315_1932'),
        ('event', '0002_event_tags'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seo',
            name='article',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='blog.Article'),
        ),
        migrations.AddField(
            model_name='seo',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='event.Event'),
        ),
        migrations.AddField(
            model_name='seo',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='team.Project'),
        ),
    ]
