# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20170317_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='sub_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Слоган'),
        ),
    ]
