# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_auto_20170317_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='card_name',
            field=models.CharField(default='', max_length=300, verbose_name='Название в списке'),
        ),
    ]
