# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170315_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
