# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-datetime_create',), 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
